name: null                          # Our env was made with --prefix
channels:
  - conda-forge                     # third party stuff
  - defaults
  - etamsen
dependencies:
  #- python=3.7
  - pip:
    - probeye==1.0.6
    - rdflib==5.0.0
  - matplotlib
  - doit
  - pyyaml
  - mkl
  - mkl-service
  - fenics_concrete
#  - flake8
#  - sphinx
#  - sphinx_rtd_theme
#  - conda-ecosystem-user-package-isolation
  
  
