name: lebedigital
channels:
  - conda-forge                     # third party stuff
  - bioconda                        # snakemake
  - bam77
  - defaults
dependencies:
  - python>=3.10
  - pip
  - matplotlib
  - mamba
  - scipy
  - doit
  - docker-compose
  - cython
  - numpy
  - pandas
  - pyyaml
  - owlready2
  - rdflib=6
  - sparqlwrapper
  - requests
  - gitpython
  - pyshacl
  - conda-ecosystem-user-package-isolation
  - fenicsxconcrete
  - python-graphviz
  - pytest
  - xlrd
  - openpyxl
  - tectonic=0.8
  - pint=0.20
  - pint-pandas
  - snakemake
  - pybis=1.35.5
  - xlsxwriter
  - termcolor
  - sphinx
  - pytest-cov
  - codecov
  - pydantic<2.0
  - seaborn
  - pip:
    - probeye==2.3.0
    - -e .
