name: lebedigital
channels:
  - conda-forge                     # third party stuff
  - etamsen
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - matplotlib
  - mamba
  - scipy
  - cython
  - numpy
  - pandas
  - pyyaml
  - gitpython
  - fenics_concrete
  - python-graphviz
  - pytest
  - pip
  - jupyter
  - jupyterlab
  - pytorch
  - torchvision
  - torchtext
  - pip:
    - torchviz
    - -e .
    
    
