name: null                          # Our env was made with --prefix
channels:
  - conda-forge                     # third party stuff
  - defaults
dependencies:
  - python=3.7
  - pip
  - matplotlib
  - pymc3=3.9.3
  - doit
  - pyyaml
  - mkl
  - mkl-service
  - docker-compose
  - Cython==0.29.15
  - numpy
  - pandas
  - Owlready2==0.33
  - rdflib==6.1.1
  - SPARQLWrapper==1.8.5
  - requests==2.22.0
  - GitPython==3.1.24
  - probeye==1.0.6
  - pyaml==21.10.1
#  - flake8
#  - sphinx
#  - sphinx_rtd_theme
#  - conda-ecosystem-user-package-isolation
  
  



