name: null                          # Our env was made with --prefix
channels:
  - conda-forge                     # third party stuff
  - defaults
dependencies:
  - python=3.7
  - pip
  - matplotlib
  - pymc3=3.9.3
  - doit
  - pyyaml
  - mkl
  - mkl-service
  - docker-compose
#  - flake8
#  - sphinx
#  - sphinx_rtd_theme
#  - conda-ecosystem-user-package-isolation
  
  



