name: null                          # Our env was made with --prefix
channels:
  - conda-forge                     # third party stuff
  - defaults
dependencies:
  - python=3.9
  - pip
  - matplotlib
  - pymc3=3.11
  - doit
  - pyyaml
  - mkl
  - mkl-service
  - flake8
  - sphinx
  - sphinx_rtd_theme
  - conda-ecosystem-user-package-isolation
  
  



