name: lebedigital
channels:
  - conda-forge                     # third party stuff
  - etamsen
  - defaults
dependencies:
  - python=3.9.7
  - matplotlib
  - mamba
  - scipy
  - doit
  - docker-compose
  - cython
  - numpy
  - pandas
  - pyyaml
  - owlready2
  - rdflib
  - sparqlwrapper
  - seaborn
  - requests
  - gitpython
  - pyshacl
  - conda-ecosystem-user-package-isolation
  - fenics_concrete
  - pytest
  - pip
  - pip:
    - probeye==2.3.0
    - -e .
