name: lebedigital
channels:
  - conda-forge                     # third party stuff
  - bioconda                        # snakemake
  - bam77
  - defaults
dependencies:
  - python=3.9.7
  - pip
  - matplotlib
  - mamba
  - scipy
  - doit
  - docker-compose
  - cython
  - numpy
  - pandas=2.0.3
  - pyyaml
  - owlready2
  - rdflib=6
  - sparqlwrapper
  - requests
  - gitpython
  - pyshacl
  - conda-ecosystem-user-package-isolation
  - fenics_concrete
  - python-graphviz
  - pytest
  - xlrd
  - tectonic=0.8
  - pint=0.20
  - pint-pandas
  - snakemake
  - termcolor
  - sphinx
  - pytest-cov
  - codecov
  - seaborn
  - extpybis
  - pip:
    - probeye==2.3.0
    - -e .
