name: Deploy

env:
  ONTOLOGY_FILE_NAME: lebedigital/ConcreteOntology/BaseOntology/cpto.ttl
  
on:
    workflow_dispatch:
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
    ## First step: Checkout main from the repository
    - uses: actions/checkout@v3
      with:
        path: deploy_main
    ## Second step: Use the get_ontoversion tool to get the current ontology version published in main
    ## Usage of get_ontoversionversion.py:
    ##   python get_ontoversionversion.py [-l L]
    ##     -l L    Location of the ontology file
    ##             default: main/ontology.ttl
    - name: Get ontology version
      run: |
           pip install rdflib
           echo "ONTO_VERSION=$(python deploy_main/.github/workflows/get_ontoversion.py deploy_main/$ONTOLOGY_FILE_NAME)" >> "$GITHUB_ENV"
    ## Third step: Build HTML and ontology serializations for the current version
    - name: Build HTML for main
      run: | 
           wget -O widoco.jar https://github.com/dgarijo/Widoco/releases/download/v1.4.17/java-11-widoco-1.4.17-jar-with-dependencies.jar
           mkdir public 
           mkdir public/v$ONTO_VERSION
           java -jar widoco.jar -ontFile deploy_main/$ONTOLOGY_FILE_NAME -outFolder public/v$ONTO_VERSION -htaccess -uniteSections -includeAnnotationProperties -lang en-de -getOntologyMetadata -noPlaceHolderText -rewriteAll -webVowl
           cp public/v$ONTO_VERSION/index-en.html public/v$ONTO_VERSION/index.html
    ## Fourth step: Publish HTML docs and ontology serializations to gh pages
    ##              maintaining other versions and
    ##              replacing the current version (if existing)
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: gh-pages
        build_dir: public
        keep_history: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}