name: lebedigital
on:
  push:
    branches-ignore:

  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CACHE_NUMBER: 2  # increase to reset cache manually

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      OPENBIS_STATE_DIR: openbis/openbis_state

    steps:
      - name: build docker
        run: |
          mkdir -p $OPENBIS_STATE_DIR
          docker run -d --name=openbis -e SERVER_HOST_PORT="localhost:443" -e GROUP_ID=12940 -e GROUP_NAME="docker-host-folder-group" -e CORE_PLUGINS='enabled-modules = dropbox-monitor, dataset-uploader, dataset-file-search, xls-import, openbis-sync, eln-lims, openbis-ng-ui, search-store' -v /home/$OPENBIS_STATE_DIR:/home/openbis/openbis_state -p 8443:443 --restart=always openbis/debian-openbis:20.10.4

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-variant: Mambaforge
            miniforge-version: latest
            activate-environment: lebedigital
            use-mamba: true

      - name: Set cache date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - uses: actions/cache@v2
        with:
          path: "/usr/share/miniconda3/envs/lebedigital"
          key: conda-${{ hashFiles('environment.yml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
        id: cache

      - name: Update environment
        run: mamba env update -n lebedigital -f environment.yml
        if: steps.cache.outputs.cache-hit != 'true'

      - name: set default docker settings
        shell: bash -l {0}
        run: |
          cd $GITHUB_WORKSPACE/usecases/openbis_docker_setup/
          python3 -m init_settings_docker --login admin --password changeit --url https://localhost:8443/openbis/

      - name: pytest
        id: pytest
        shell: bash -l {0}
        run: |
          cd $GITHUB_WORKSPACE/tests/
          pytest -s --login admin --password changeit --ignore=paper_workflow --ignore=demonstrator_calibration/test_sampler.py --ignore=demonstrator_scripts/test_column_plus_homogenization.py # some weird .ito issue. No idea what it is

      - name: run-minimum-working-example
        shell: bash -l {0}
        run: |
          cd $GITHUB_WORKSPACE/usecases/MinimumWorkingExample/
          doit runson=docker dataset_upload=no

      - name: run-optimization-workflow
        shell: bash -l {0}
        run: |
          cd $GITHUB_WORKSPACE/usecases/optimization_paper/optimization_workflow/
          snakemake -c 1

      - name: run-usecase-mode_learning
        shell: bash -l {0}
        run: |
          cd $GITHUB_WORKSPACE/usecases/optimization_paper/model_learning/homogenization/exp_5
          python homogenization_model_calibration.py
      # Issue with Latex installation in runner. Anyway the paper is in Overleaf, so this obsolete/unnecessary
      # - name: run-optimization-paper
      #   shell: bash -l {0}
      #   run: |
      #     cd $GITHUB_WORKSPACE/usecases/optimization_paper/
      #     doit

      - name: Archive results of minimum working example
        uses: actions/upload-artifact@v3
        with:
            name: minimum_working_example_results
            path:  |
              usecases/MinimumWorkingExample/emodul/
              usecases/MinimumWorkingExample/mixture/

      # - name: Archive optimization paper pdf
      #   uses: actions/upload-artifact@v3
      #   with:
      #       name: optimization_paper
      #       path: |
      #         usecases/optimization_paper/tex/optimization_paper.pdf
      #         usecases/optimization_paper/figures/
      #         usecases/optimization_paper/optimization_workflow/Results
              

