name: lebedigital
on:
  push:
    branches-ignore:

  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Runs the workflow once per day at 3:15am
  schedule:
    - cron: '3 15 * * *'

env:
  CACHE_NUMBER: 2  # increase to reset cache manually

jobs:
  tests:
    runs-on: ubuntu-latest

    outputs:
      branch_coverage: ${{ steps.pytest.outputs.coverage }}
      coverage_report: ${{ steps.pytest.outputs.report }}

    steps:
      - name: build docker
        run: |
          mkdir data 
          ls -a
          docker create --name=openbis -e SERVER_HOST_PORT="localhost:443" -e GROUP_ID=12940 -e GROUP_NAME="docker-host-folder-group" -e CORE_PLUGINS='enabled-modules = dropbox-monitor, dataset-uploader, dataset-file-search, xls-import, openbis-sync, eln-lims, openbis-ng-ui, search-store' -v /home/data/:/home/openbis/openbis_state -p 8443:443 --restart=always openbis/debian-openbis:latest
          docker start openbis
          ls -a

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-variant: Mambaforge
            miniforge-version: latest
            activate-environment: lebedigital
            use-mamba: true

      - name: Set cache date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - uses: actions/cache@v2
        with:
          path: "/usr/share/miniconda3/envs/lebedigital"
          key: conda-${{ hashFiles('environment.yml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
        id: cache

      - name: Update environment
        run: mamba env update -n lebedigital -f environment.yml
        if: steps.cache.outputs.cache-hit != 'true'

      - name: pytest
        id : pytest
        shell: bash -l {0}
        run: |
          coverage run -m pytest -s -W error::UserWarning && coverage xml
          COVERAGE_REPORT=$(coverage report -m | tee /dev/stderr)
          #cd $GITHUB_WORKSPACE/tests/
          #pytest -s -m "not login" --cov ../lebedigital --cov-report=xml  --login admin --password changeit # testing coverage!!!
          #coverage report -m

      - name: run-minimum-working-example
        shell: bash -l {0}
        run: |
          cd $GITHUB_WORKSPACE/usecases/MinimumWorkingExample/
          doit runson=docker dataset_upload=no

      - name: run-optimization-workflow
        shell: bash -l {0}
        run: |
          cd $GITHUB_WORKSPACE/usecases/optimization_paper/optimization_workflow/
          snakemake -c 1

      - name: run-optimization-paper
        shell: bash -l {0}
        run: |
          cd $GITHUB_WORKSPACE/usecases/optimization_paper/
          doit

      - name: Archive results of minimum working example
        uses: actions/upload-artifact@v3
        with:
            name: minimum_working_example_results
            path:  |
              usecases/MinimumWorkingExample/emodul/
              usecases/MinimumWorkingExample/mixture/

      - name: Archive optimization paper pdf
        uses: actions/upload-artifact@v3
        with:
            name: optimization_paper
            path: |
              usecases/optimization_paper/tex/optimization_paper.pdf
              usecases/optimization_paper/figures/
              usecases/optimization_paper/optimization_workflow/Results
              
