name: lebedigital
on: [push]

# Allows you to run this workflow manually from the Actions tab
workflow_dispatch:

jobs:
  minimum-working-example:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: setup-conda-environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yaml
          miniforge-version: latest
          activate-environment: lebedigital

      - name: create data folder
        run: |
          mkdir ${GITHUB_WORKSPACE}/usecases/Concrete/Example/emodul/
          mkdir ${GITHUB_WORKSPACE}/usecases/Concrete/Example/emodul/metadata_yaml_files
          mkdir ${GITHUB_WORKSPACE}/usecases/Concrete/Example/emodul/processeddata

      - name: run-workflow
        shell: bash -l {0}
        run: |
          conda install --channel conda-forge doit=0.33.1
          cd $GITHUB_WORKSPACE/usecases/Concrete/Example/
          doit
 