name: lebedigital
on:
  push:
    branches-ignore:

  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Runs the workflow once per day at 3:15am
  schedule:
    - cron: '3 15 * * *'

env:
  CACHE_NUMBER: 2  # increase to reset cache manually

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      OPENBIS_STATE_DIR: openbis/openbis_state

    outputs:
      branch_coverage: ${{ steps.pytest.outputs.coverage }}
      coverage_report: ${{ steps.pytest.outputs.report }}

    steps:
      - name: build docker
        run: |
          mkdir -p $OPENBIS_STATE_DIR
          ls -a
          docker create --name=openbis -e SERVER_HOST_PORT="localhost:443" -e GROUP_ID=12940 -e GROUP_NAME="docker-host-folder-group" -e CORE_PLUGINS='enabled-modules = dropbox-monitor, dataset-uploader, dataset-file-search, xls-import, openbis-sync, eln-lims, openbis-ng-ui, search-store' -v /home/$OPENBIS_STATE_DIR:/home/openbis/openbis_state -p 8443:443 --restart=always openbis/debian-openbis:latest
          docker start openbis
          ls -a
          cd openbis
          ls -a
          cd ..

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-variant: Mambaforge
            miniforge-version: latest
            activate-environment: lebedigital
            use-mamba: true

      - name: Set cache date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - uses: actions/cache@v2
        with:
          path: "/usr/share/miniconda3/envs/lebedigital"
          key: conda-${{ hashFiles('environment.yml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
        id: cache

      - name: Update environment
        run: mamba env update -n lebedigital -f environment.yml
        if: steps.cache.outputs.cache-hit != 'true'

      - name: set default docker settings
        shell: bash -l {0}
        run: |
          cd $GITHUB_WORKSPACE/usecases/openbis_docker_setup/
          python3 -m init_settings_docker --login admin --password changeit --url https://localhost:8443/openbis/

      - name: pytest
        id: pytest
        shell: bash -l {0}
        run: |
          cd $GITHUB_WORKSPACE/tests/
          pytest -s --cov ../lebedigital --cov-report=xml --login admin --password changeit
          COVERAGE_REPORT=$(coverage report -m | tee /dev/stderr)
          
          # passing a multiline string to output to use it in next job
          echo "report<<EOF" >> $GITHUB_OUTPUT
          echo "$COVERAGE_REPORT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
          # extract the percentage of the total coverage, e.g. `75%`
          COVERAGE_PCT=$(echo $COVERAGE_REPORT | grep -oP "TOTAL\s+\d+\s+\d+\s+(\d+%)" | grep -oP "\d+%")
          
          # get only the coverage number without the percentage symbol
          COVERAGE_NUM=$(echo $COVERAGE_PCT | grep -oP "\d+")
          
          # active branch name
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
          
          # add them to the github env for later usage
          echo "COVERAGE_NUM=$(echo $COVERAGE_NUM)" >> $GITHUB_ENV
          echo "coverage=$(echo $COVERAGE_NUM)" >> $GITHUB_OUTPUT  # to be used in next job
          echo "COVERAGE_PCT=$(echo $COVERAGE_PCT)" >> $GITHUB_ENV
          
          # removing all possible slashes in file names, they seem to appear during Pull Requests
          echo "BRANCH_NAME=$(echo $BRANCH_NAME | sed "s/\//_/g")" >> $GITHUB_ENV

      - name: run-minimum-working-example
        shell: bash -l {0}
        run: |
          cd $GITHUB_WORKSPACE/usecases/MinimumWorkingExample/
          doit runson=docker dataset_upload=no

      - name: run-optimization-workflow
        shell: bash -l {0}
        run: |
          cd $GITHUB_WORKSPACE/usecases/optimization_paper/optimization_workflow/
          snakemake -c 1

      - name: run-optimization-paper
        shell: bash -l {0}
        run: |
          cd $GITHUB_WORKSPACE/usecases/optimization_paper/
          doit

      - name: Archive results of minimum working example
        uses: actions/upload-artifact@v3
        with:
            name: minimum_working_example_results
            path:  |
              usecases/MinimumWorkingExample/emodul/
              usecases/MinimumWorkingExample/mixture/

      - name: Archive optimization paper pdf
        uses: actions/upload-artifact@v3
        with:
            name: optimization_paper
            path: |
              usecases/optimization_paper/tex/optimization_paper.pdf
              usecases/optimization_paper/figures/
              usecases/optimization_paper/optimization_workflow/Results
              

      - name: Create Coverage Badge
        if: contains(env.BRANCH_NAME, 'main')
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: c10a5b6d0714b1fe2344eb60918e92f8
          filename: lebedigital_${{ env.BRANCH_NAME }}_coverage.json
          label: coverage
          message: ${{ env.COVERAGE_PCT }}
          valColorRange: ${{ env.COVERAGE_PCT }}
          maxColorRange: 95  # value where ligth green starts
          minColorRange: 50  # value where red starts
              

  check_coverage:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: check coverage
        run: |
          # getting coverage number from output of first job for this branch
          BRANCH_COVERAGE=${{ needs.tests.outputs.branch_coverage }}
          echo "Coverage of current branch: $BRANCH_COVERAGE %"
          declare -i int_branch_coverage=$BRANCH_COVERAGE
          
          # getting coverage number from gist for main branch
          MAIN_DATA=$(curl -s -X GET "https://gist.githubusercontent.com/eriktamsen/c10a5b6d0714b1fe2344eb60918e92f8/raw/lebedigital_main_coverage.json")
          MAIN_COVERAGE=$(echo $MAIN_DATA | grep -o -P 'message.{3,6}' | sed -e 's/"//g' | sed -e 's/://g' | sed -e 's/message//g' | sed -e 's/%//g' | sed -e 's/,//g')
          echo "Coverage of main branch: $MAIN_COVERAGE %"
          declare -i int_main_coverage=$MAIN_COVERAGE
          
          # compute difference
          delta_coverage=$(( int_branch_coverage - int_main_coverage  ))
          echo "Increase in coverage: $delta_coverage %"
          
          echo "Coverage report:"
          echo "-----------------------------------------------------------------------------------------------"
          echo "${{ needs.tests.outputs.coverage_report }}"
          echo "-----------------------------------------------------------------------------------------------"
          
          if [[ $delta_coverage -lt 0 ]]
          then
            echo "The current branch has lower coverage than the main branch, please improve your code"
            exit 1
          fi
          echo "Passing!!!"
              
