name: lebedigital minimum working example
on: [push]

jobs:
  build-knowledge-graph:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: install python packages
        uses: py-actions/py-dependency-install@v2
        with:
          path: "usecases/Concrete/Example/requirements.txt"
      - name: create data folder
        run: |
          mkdir ${GITHUB_WORKSPACE}/usecases/Concrete/Example/emodul/
          mkdir ${GITHUB_WORKSPACE}/usecases/Concrete/Example/emodul/metadata_yaml_files
          mkdir ${GITHUB_WORKSPACE}/usecases/Concrete/Example/emodul/processeddata
      - name: run pydoit
        run: |
          cd usecases/Concrete/Example/
          doit
 