name: lebedigital minimum working example
on: [push]

jobs:
  build-knowledge-graph:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: install python packages
        uses: py-actions/py-dependency-install@v2
        with:
          path: "usecases/Concrete/knowledgeGraph/requirements.txt"
      - name: run pydoit
        run: |
          cd usecases/Concrete/knowledgeGraph
          doit
 