name: interbis
on:
  push:
    branches-ignore:

  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  URL: https://localhost:8443/openbis/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build docker
        run: |
          mkdir data 
          ls -a
          docker create --name=openbis -e SERVER_HOST_PORT="localhost:443" -e GROUP_ID=12940 -e GROUP_NAME="docker-host-folder-group" -e CORE_PLUGINS='enabled-modules = dropbox-monitor, dataset-uploader, dataset-file-search, xls-import, openbis-sync, eln-lims, openbis-ng-ui, search-store' -v /home/data/:/home/openbis/openbis_state -p 8443:443 --restart=always openbis/debian-openbis:latest
          docker start openbis
          ls -a

      - name: checkout repo
        uses: actions/checkout@v3

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-variant: Mambaforge
            miniforge-version: latest
            activate-environment: lebedigital
            use-mamba: true

      - name: Set cache date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - uses: actions/cache@v2
        with:
          path: "/usr/share/miniconda3/envs/lebedigital"
          key: conda-${{ hashFiles('environment.yml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
        id: cache

      - name: Update environment
        run: mamba env update -n lebedigital -f environment.yml
        if: steps.cache.outputs.cache-hit != 'true'

      - name: run-interbis-pytest
        shell: bash -l {0}
        run: |
          cd $GITHUB_WORKSPACE/tests/
          pytest -v -m "login" --login admin --password changeit 
