# This workflow will install Python dependencies, run tests with concrete model

name: Tests for the fem model

on: [push]

jobs:
  test_model:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: "3.9"
        mamba-version: "*"
        channels: conda-forge, etamsen
        channel-priority: strict
        auto-update-conda: true  
        environment-file: environment_sim.yml
    
    - name: Run tests
      shell: bash -l {0}
      run: |
        pytest -s -W error::UserWarning
        # pytest usecases/Concrete/tests/ -s -W error::UserWarning
